### PR TITLE
Create EZStrings

### PR DESCRIPTION
**Pull request by brianconcannon2**
Handy routines for handling strings.  If this code is acceptable, I will add many more comments and subroutines and functions that I have in my personal toolbox of Fortran code.

### CODE REVIEW

**Comment by ShrirajHegde** [comment]
Thank you.
can you add the module ```VICA_VARS```

I am unable to find the module. 

It would be great if you contribute. From next pull requests, please use testing branch.

**Comment by ShrirajHegde** [comment]
You are very very welcome to contribute. Can't stress this enough.

**Comment by ShrirajHegde** [comment]
This is fortran77 right? I am renaming repo to just Fortran instead of fortran90

Please go ahead and add all you can. It would be a great help since it is hard to find snippets and help for Fortran online.

**Comment by brianconcannon2** [comment]
Shriraj,
Thanks for your enthusiasm, it inspires me to spend a lot of time on this.
I will be careful about testing and documentation before posting again.


Regards - BRIAN CONCANNON           262.442.6324 (M) 

    On Sunday, October 4, 2020, 10:18:08 AM CDT, Shriraj Hegde <notifications@github.com> wrote:  
 
 


This is fortran77 right? I am renaming repo to just Fortran instead of fortran90

Please go ahead and add all you can. It would be a great help since it is hard to find snippets and help for Fortran online.

**Comment by ShrirajHegde** [comment]
Hello @brianconcannon2  can you please add ```VICA_VARS``` module so that I can merge this to master

**Comment by brianconcannon2** [comment]
Shiraj,
That module is very hundreds of excess definitions.  I need to pare it down or eliminate it by refactoring.  I intend to resume work on this.
Regards - BRIAN CONCANNON           262.442.6324 (M) 

    On Tuesday, October 13, 2020, 11:11:50 AM CDT, Shriraj Hegde <notifications@github.com> wrote:  
 
 


Hello @brianconcannon2 can you please add VICA_VARS module so that I can merge this to master

**Comment by ShrirajHegde** [comment]
sure,thank you

**Pull request merged**
